sol2:
	gcc -o ../build/sol2  main.c callbacks.c ECS/entity.c ECS/system.c graphics/model.c graphics/render.c graphics/shader.c physics/physics.c schedule/schedule.c utility/array.c utility/fileload.c utility/maths.c utility/objload.c input/input.c text/text.c -lGL -lGLEW -lglfw -lSOIL -lm -ldl -lfreetype
